// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPbdYHTulDOVaInXivg4ZlmhCuj-g7wpA',
    appId: '1:436357381387:web:11127e1fe777be4eeef60e',
    messagingSenderId: '436357381387',
    projectId: 'flexibandapp',
    authDomain: 'flexibandapp.firebaseapp.com',
    storageBucket: 'flexibandapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgM072kq_cHFhvw7MV9cGCJJ1tJcdViq8',
    appId: '1:436357381387:android:9c43315db5fbb49deef60e',
    messagingSenderId: '436357381387',
    projectId: 'flexibandapp',
    storageBucket: 'flexibandapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_y9BSPxf_Cxt-HW6OvZLvt4veH3mMTo',
    appId: '1:436357381387:ios:3df85e1f1bd713c3eef60e',
    messagingSenderId: '436357381387',
    projectId: 'flexibandapp',
    storageBucket: 'flexibandapp.appspot.com',
    androidClientId: '436357381387-3u4pdn3mlcqucodafi88k9tudpbeqr27.apps.googleusercontent.com',
    iosClientId: '436357381387-m7bc0aqlc0hslkb6j6tjeek17n40r2hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj_y9BSPxf_Cxt-HW6OvZLvt4veH3mMTo',
    appId: '1:436357381387:ios:3df85e1f1bd713c3eef60e',
    messagingSenderId: '436357381387',
    projectId: 'flexibandapp',
    storageBucket: 'flexibandapp.appspot.com',
    androidClientId: '436357381387-3u4pdn3mlcqucodafi88k9tudpbeqr27.apps.googleusercontent.com',
    iosClientId: '436357381387-m7bc0aqlc0hslkb6j6tjeek17n40r2hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKPv9bl5k5zFpImBOyPunFS-_S94okIOY',
    appId: '1:436357381387:web:50475cc92fcb8464eef60e',
    messagingSenderId: '436357381387',
    projectId: 'flexibandapp',
    authDomain: 'flexibandapp.firebaseapp.com',
    storageBucket: 'flexibandapp.appspot.com',
  );
}
